server:
  port: 9000

spring:
  application:
    name: rsw-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb?currentSchema=spring
    username: auth_server_user
    password: s0ho-shenanigan
    type: org.apache.tomcat.jdbc.pool.DataSource
    platform: postgres

logging:
  level:
    org.springframework.security: info

security:
  oauth2:
    client:
      clientId: rsw
      clientSecret: rswsecret
      scope: read,write
      autoApproveScopes: '.*'
#      authorized-grant-types: authorization_code,client_credentials,refresh_token
      authorities: USER, ADMIN
# oauth2 resource server filter order changed to -1 in Spring Boot 1.5; setting back to previous working order
    resource:
      filterOrder: 3
  basic:
    enabled: false
  sessions: stateless
  user:
    password: password

auth:
  security:
    jwt:
      signingKey: abracadabra
      validityDurationSecs: 3600
    # pattern requires at least one of each: lowercase, uppercase, digit and special char, min 6 max 15
    password:
      pattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%\^\-_+=])[a-zA-Z0-9!@#$%\^\-_+=]{6,15}$
      expireDays: 90
      recycleSpan: 5
#  tokenType: oauth2
  tokenType: jwt
