server:
  port: 9000

spring:
  application:
    name: rsw-auth

gateway:
  demo:
    tokenType: oauth2
#    tokenType: jwt

logging:
  level:
    org.springframework.security: debug

security:
  oauth2:
    client:
      client-id: rsw
      client-secret: rswsecret
      scope: read,write,blue
      auto-approve-scopes: '.*'
#      authorized-grant-types: authorization_code,client_credentials,refresh_token
      authorities: USER, ADMIN
  basic:
    enabled: false
  sessions: stateless
  user:
    password: password

rsw:
  security:
    jwt:
      signingKey: abracadabra

