apiVersion: v1
kind: Service
metadata:
  name: rsw-auth
  labels:
    app: rsw-auth
    role: auth
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: rsw-auth
    role: auth
    tier: backend
