apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
    role: auth
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: auth-server
    role: auth
    tier: backend
