apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rsw-auth
# deployment/replication controller spec
# running only one instance of the auth server to avoid needing a persistent store when NOT using JWT
spec:
  replicas: 1
# pod template
  template:
    metadata:
      labels:
        app: rsw-auth
        role: auth
        tier: backend
# pod spec
    spec:
      containers:
      - name: rsw-auth
        image: gcr.io/inspired-nomad-149920/rsw-auth:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 1024M
        ports:
        - containerPort: 9000
